import { useState, useEffect } from 'react';
import { getSkillTree } from '../services/api';
import { Link } from 'react-router-dom';
import { Brain, BookOpen, ChevronRight } from 'lucide-react';

export default function SkillTree() {
  const [tree, setTree] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getSkillTree()
      .then(({ data }) => setTree(data))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  if (loading) return (
    <div className="min-h-screen bg-bg-primary flex items-center justify-center">
      <div className="w-10 h-10 border-4 border-accent-primary border-t-transparent rounded-full animate-spin" />
    </div>
  );

  return (
    <div className="min-h-screen bg-bg-primary">
      <main className="max-w-5xl mx-auto px-6 py-10">
        <div className="text-center mb-16 animate-fade-in">
          <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl mb-5"
            style={{ background: 'linear-gradient(135deg, rgba(167,139,250,0.15), rgba(139,92,246,0.15))', border: '1px solid rgba(139,92,246,0.25)' }}>
            <Brain className="w-10 h-10 text-accent-primary" />
          </div>
          <h1 className="text-3xl font-bold text-text-primary mb-2">My AI Skill Tree</h1>
          <p className="text-text-secondary">Personalized learning roadmap generated by AI based on your performance</p>
        </div>

        <div className="relative space-y-20 flex flex-col items-center">
          {/* Connecting Line */}
          <div className="absolute top-0 bottom-0 left-1/2 -translate-x-1/2 w-0.5 bg-gradient-to-b from-accent-primary/50 via-accent-primary/20 to-transparent z-0" />

          {tree?.tiers.map((tier, idx) => (
            <div key={idx} className="relative z-10 w-full animate-slide-up" style={{ animationDelay: `${idx * 0.2}s` }}>
              <div className="flex flex-col items-center mb-8">
                <div className="px-6 py-2 rounded-full bg-bg-secondary border border-border-default text-xs font-bold uppercase tracking-widest text-accent-primary mb-6 shadow-xl shadow-black/50">
                  {tier.name}
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 w-full">
                  {tier.topics.map((topic, tidx) => (
                    <div key={tidx} className="glass p-6 rounded-2xl border-border-default hover:border-accent-primary/30 transition-all group">
                      <div className="w-10 h-10 rounded-xl bg-bg-tertiary flex items-center justify-center mb-4 group-hover:bg-accent-primary/10 transition-colors">
                        <BookOpen className="w-5 h-5 text-accent-primary" />
                      </div>
                      <h3 className="text-text-primary font-bold mb-2 group-hover:text-accent-primary transition-colors">{topic.title}</h3>
                      <p className="text-xs text-text-secondary leading-relaxed mb-4 line-clamp-3">
                        {topic.reason}
                      </p>
                      <Link 
                        to={`/topic/${topic.id}`}
                        className="text-[11px] font-bold text-accent-primary flex items-center gap-1 hover:gap-2 transition-all"
                      >
                        LEARN NOW <ChevronRight className="w-3 h-3" />
                      </Link>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-20 text-center animate-fade-in" style={{ animationDelay: '1s' }}>
          <p className="text-sm text-text-muted italic">
            "The journey of a thousand code blocks begins with a single console.log()"
          </p>
        </div>
      </main>
    </div>
  );
}
